name: Code Quality Check

on:
  push:
    branches: [main]

jobs:
  code-quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install htmlhint stylelint prettier eslint eslint-config-prettier eslint-plugin-prettier

      - name: Run HTMLHint
        run: npx htmlhint **/*.html

      - name: Run ESLint
        run: npx eslint .

      - name: Run Stylelint
        run: npx stylelint "**/*.{css,scss}"

      - name: Run Prettier
        run: npx prettier --check "**/*.{html,js,css,scss}"
