name: Code Quality Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.4.2

    - name: Install dependencies
      run: |
        npm install -g eslint prettier htmlhint stylelint
        npm install --save-dev eslint-config-prettier eslint-plugin-prettier eslint-plugin-html stylelint-config-standard stylelint-scss

    - name: ESLint
      run: npx eslint .

    - name: Prettier
      run: npx prettier --check .

    - name: HTMLHint
      run: npx htmlhint .

    - name: Stylelint
      run: npx stylelint "**/*.{css,scss}"
