name: lint-and-format

on:
  push:
    branches: [ main ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run HTML linter
      - name: HTML Lint
        run: npx htmlhint .

      # Run ESLint
      - name: ESLint
        run: npx eslint .

      # Run Prettier
      - name: Prettier
        run: npx prettier --check .

      # Run Stylelint
      - name: Stylelint
        run: npx stylelint "**/*.css"
